services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src

    