services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
  db:
    image: postgres:17.4-bookworm
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

    