services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:17.4-bookworm
    env_file:
      - path: "./backend/.env"
        required: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: